version: '3.8'

services:
  database:
    image: mongo-2
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - app-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    ports:
      - "5003:5000"
    depends_on:
      - database
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - app-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
    user: "1000:1000"
    read_only: true


  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend
    ports:
      - "3003:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
    user: "1000:1000"
    read_only: true


volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge




